package com.atguigu.mybatis.bean;

public class WhUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_user.id
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_user.name
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_user.id
     *
     * @return the value of ll_user.id
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_user.id
     *
     * @param id the value for ll_user.id
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_user.name
     *
     * @return the value of ll_user.name
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_user.name
     *
     * @param name the value for ll_user.name
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    
    @Override
    public String toString() {
        return "{"+id+","+name+"}";
    }
}