package com.atguigu.mybatis.mapper;

import com.atguigu.mybatis.bean.WhUser;
import java.util.List;

public interface WhUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_user
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_user
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    int insert(WhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_user
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    WhUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_user
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    List<WhUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_user
     *
     * @mbggenerated Tue Jul 11 11:21:22 CST 2023
     */
    int updateByPrimaryKey(WhUser record);
}